Chia-Network/cadt-ui

src/components/forms/SplitUnitForm.js

fix: split forms issue

---

src/components/blocks/DetailedViewStagingTab.js
src/components/blocks/DetailedViewTab.js
src/components/blocks/StagingDataGroups.js

detailed view fixed
staging cards
staging detailed view fixed

fix: wrap text to next line

---

src/components/form/SimpleSelect.js

on mouse hover the user will be displayed exactly the full length of the text

feat: select solution when item length more than max

---

src/components/blocks/StagingDataGroups.js
src/components/icons/ReloadIcon.js
src/components/icons/index.js
src/pages/Projects/index.js
src/pages/Units/index.js
src/store/actions/climateWarehouseActions.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

feat: add failed tab

---

.env
src/components/blocks/LeftNav.js

feat: add package json number to app

---

src/components/forms/CreateUnitIssuanceForm.js

fix: reusing an issuance on a unit deletes it from the project it was created on

---

src/App.js
src/components/blocks/LeftNav.js
src/components/layout/SocketStatusContainer.js

fix: move status container to right bottom corner

---

src/components/blocks/Modal.js
src/navigation/AppNavigator.js

fix: added Connect to Network Error Modal

---

src/components/form/SimpleSelect.js
src/components/forms/ProjectDetailsForm.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

Added "Add Unlisted Registry Of Origin"
Selecting "Add Unlisted Registry of Origin" adds input field
New Registry Of Origin Added

feat: add input to registry of origin

---

src/components/forms/ProjectDetailsForm.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

Added "Added Unlisted Registry"
Select "Added Unlisted Registry" adds Input field
elect "Added Unlisted Registry" adds Input field
New Registry

feat: add input to current registry

---

src/utils/formatData.js
src/utils/functionUtils.js

Green for "INSERTS", RED for "DELETED", default color for not changed

Fix: Update Staging Detailed View

---

src/components/form/SelectOrganizations.js
src/components/forms/CreateOrgForm.js
src/pages/Organization/index.js
src/store/actions/climateWarehouseActions.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

feat: add png support for organization #681

---

src/pages/Projects/index.js
src/pages/Units/index.js
src/store/actions/climateWarehouseActions.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

feat: add clean staging button for v1/staging/clean #288

---

src/components/blocks/DetailedViewIssuanceUnitTable.js
src/components/blocks/ProjectIssuanceDetails.js
src/components/blocks/index.js

without pagination (if less entries than 7)
with pagination (if more than 7 entries - for the example below for more than 1 entry)

feat: replace list with table and more details for units that belong to this issuance

---

src/components/forms/ProjectDetailsForm.js
src/store/validations/project.validations.js

Removed Required from NDC Information

fix: Removed ndc information validation logic

---

src/components/blocks/UnitsDetails.js

Switch Country and In-Country in Detail View

fix: switch country and in-country in unit detail view

---

package-lock.json
src/components/form/SelectOrganizations.js

Projects Alphabetically
Units Alphabetically
Audits Alphabetically

fix: org list arranged alphabetically

---

src/components/blocks/LeftNav.js
src/components/blocks/UnitsDetails.js
src/navigation/AppNavigator.js
src/pages/Conflicts/index.js
src/pages/index.js
src/store/actions/climateWarehouseActions.js
src/store/reducers/climateWarehouseReducer.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

feat: adit conflict audit table page

---

src/components/blocks/ProjectDetails.js
src/components/blocks/UnitsDetailViewModal.js
src/components/form/Textarea.js
src/components/forms/CreateProjectForm.js
src/components/forms/ProjectDetailsForm.js
src/store/validations/project.validations.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

New Description Field
Description Details
Edit Description Field
line-break

Add description to projects

---

src/components/form/SelectOrganizations.js

fix: make all organizations first in list

---

src/components/blocks/CommitModal.js
src/components/form/Textarea.js

fix: add multiline to commit message

---

src/navigation/AppNavigator.js

fix: remove extra disconnect in network error modal

---

src/components/forms/ProjectDetailsForm.js

Reverts Chia-Network/climate-warehouse-ui#748

Revert "fix: fallback if free text+picklist "

---

src/components/form/Textarea.js
src/components/forms/ProjectDetailsForm.js

Replaced cols with width to align description with other inputs

fix: replace cols with width

---

src/components/forms/CreateOrgForm.js
src/store/validations/organization.validation.js

PNG Icons removed if no Icons chosen

feat: make png icons optional

---

src/pages/Projects/index.js
src/pages/Units/index.js

Counter to Committed in Units
Counter To Committed Projects

feat: Added Counter to Committed

---

src/utils/functionUtils.js

fix: split unit detail view showing incorrect

---

package-lock.json
package.json
src/components/form/SelectCreatable.js
src/components/form/index.js
src/pages/Organization/index.js

**You can test the newly created component with** `          <SelectCreatable
options={['Micky', 'Mouse', 'In the house']}
onChange={val => console.log(val)}
/>`

feat: select component that also has the possibility to add new tags 

---

src/pages/Conflicts/index.js

Removed Timeout for Conflict message

fix: Remove Conflict Message Timeout

---

src/pages/Organization/index.js
src/store/actions/climateWarehouseActions.js
src/store/reducers/climateWarehouseReducer.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

feat: add wallet balance

---

.github/workflows/deploy-s3.yml
package.json

Final change - this will activate deployments on the `main` branch.

build:  remove dryrun flag, deploy to S3 for real.

---

src/components/form/SelectCreatable.js
src/components/forms/ProjectDetailsForm.js

Add dynamic picklists 

---

src/components/blocks/LeftNav.js
src/translations/tokens/en-US.json
src/translations/tokens/es.json
src/translations/tokens/ja.json

Fix: Added MyOrg/Projects/Units under Basic Registry

---

src/components/blocks/AuditItemModal.js
src/utils/functionUtils.js

fix: split unit detailed staging not all changes visible

---

src/components/forms/FileUploadModal.js
src/translations/tokens/en-US.json

Upload confirmation after user selects file

feat: added file upload confirmation

---

src/components/forms/ProjectIssuanceForm.js

Project Form Verification Body, now a dynamic picklist

feat: Add dynamic picklist to verification body

---

src/components/blocks/ProjectIssuanceDetails.js
src/components/blocks/UnitsIssuanceDetails.js
src/components/forms/ProjectIssuanceForm.js
src/components/forms/UnitIssuanceForm.js
src/translations/tokens/en-US.json

Replace issuance start/end dates

---

.github/workflows/deploy-s3.yml
package.json

Deploy main to new S3 bucket.  Old bucket get a tag deployed until some branding changes are ready to go live.

setup blue/green deployments for the UI

---

src/components/blocks/MyAccount.js
src/store/actions/app.js
src/translations/tokens/en-US.json

Changed UI slightly to remove the appearance of the API key being required. Updated signIn function to not require, but still handle, api key parameter.

fix: make api key optional

---

.github/workflows/auto-release.yml
.github/workflows/build-installers.yaml
package.json

Add commit signing for ChiaAutomation account.

Release version 1.2.1

---

.github/workflows/auto-release.yml
package.json

Re-release 1.2.1

---

src/renderer/components/blocks/forms/CoBenifetsForm.tsx
src/renderer/components/blocks/forms/EstimationsForm.tsx
src/renderer/components/blocks/forms/IssuancesForm.tsx
src/renderer/components/blocks/forms/LabelsForm.tsx
src/renderer/components/blocks/forms/ProjectForm.tsx
src/renderer/components/blocks/forms/ProjectLocationsForm.tsx
src/renderer/components/blocks/forms/RatingsForm.tsx
src/renderer/components/blocks/forms/RelatedProjectsForm.tsx
src/renderer/components/blocks/forms/SplitUnitForm.tsx
src/renderer/components/blocks/forms/UnitForm.tsx
src/renderer/components/form/Field.tsx

this pr adds asterisks to required fields on all applicable forms (namely forms related to editing/creating units and projects)

Refactor/fix/asterisks on required fields : issue #1222

---

src/renderer/components/blocks/layout/TransferManager.tsx

needs to be merged with https://github.com/Chia-Network/cadt/pull/1156

feat: removed hacked in refresh because backend fixed
